<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>AIStockTrader.WPF</RootNamespace>
    <ApplicationTitle>AI智能炒股助手</ApplicationTitle>
    <AssemblyName>AIStockTrader.WPF</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>



</Project>
